export const REQUIRED_HEADERS = [
  "BANK",
  "Agent id",
  "Agent Name",
  "Contact No",
  "CLUSTER VILLAGE ID",
  "CLUSTER VILLAGE NAME",
  "BRANCH CODE",
  "BRANCH NAME",
  "DATE OF JOINING",
  "Panchayat",
  "Mandal",
  "District",
  "Region",
  "OD AccountNo",
  "State",
  "DLM_DeviceId",
  "Phase",
  "Gender",
];
